name: sweet_bonanza_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  auto_route: ^8.0.3
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  flutter_countdown_timer: ^4.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Blinker
      fonts:
        - asset: fonts/Blinker-Black.ttf
        - asset: fonts/Blinker-Bold.ttf
        - asset: fonts/Blinker-ExtraBold.ttf
        - asset: fonts/Blinker-Light.ttf
        - asset: fonts/Blinker-Regular.ttf
        - asset: fonts/Blinker-SemiBold.ttf


